model_ckpt: distilbert/distilbert-base-uncased
max_len: 256
val_size: 0.1
seed: 42

output_dir: runs/distilbert-base-uncased-imdb
learning_rate: 3e-5
per_device_train_batch_size: 16
per_device_eval_batch_size: 32
num_train_epochs: 3
weight_decay: 0.01
warmup_ratio: 0.06

eval_steps: 500
save_steps: 500
logging_steps: 100
save_total_limit: 2
fp16: true
report_to: none
